### PR TITLE
fix: refactored lib folder patterns surrounding posts + showcases

### LINKED ISSUE #302: CMS: Audit logic/types around News and Showcase system
The News posts are collected and presented on the frontend with a set of code that I found in an example repo. When I created the Showcase category, I just duplicated much of this setup, but in some cases the lines may still be blurry, or there may be unnecessary duplicative code between the systems. This ticket is for a general audit and cleanup of these two systems, with an eye toward the fact that we will be adding a third category of content, Guides, in the relatively near future.

### PR DESCRIPTION
**Pull request by bodom0015**
## Problem
There is quite a bit of copy-pasted code between the Posts + Showcases

We would like a better pattern for adding new categories to avoid copy-pasting as much in the future

Redo of #312 

Fixes #302 

## Approach
* fix: restructured PostLayout + Showcase into `src/components/Layout`
* fix: refactor PostLayout + ShowcaseLayout slightly to more easily include new categories in the future (e.g. Guides, see #317)
* fix: refactor lib folder to cut down on some of the copy-pasted bits - maintain separate implementations for these resources
    * NOTE: After cleaning up this code, the Showcases are no longer sorted by Date - this will be fixed by #303 

## How to Test
1. Navigate to the list of "Project News" (PostList / PostItem): http://localhost:3000/news
    * You should see no changes compared to production: https://sdohplace.org/news
2. Choose an article (Layout -> PostLayout): http://localhost:3000/news/finding-healthy-food-connecticut
    * You should see no changes compared to production: https://sdohplace.org/news/finding-healthy-food-connecticut
    * NOTE: Images appear differently here, but these are not style changes - production appears to use different screenshot paths than dev
    * NOTE: Copyright symbol (at the bottom) has moved to the left a few pixels - I could not track down why, but this is barely noticeable
3. Navigate to the list of "Fellow Showcases" (ShowcaseList / ShowcaseItem): http://localhost:3000/showcase
    * You should see no changes compared to production: https://sdohplace.org/showcase
    * NOTE: Images appear differently here, but these are not style changes - production appears to use different screenshot paths than dev
4. Choose a showcase (Layout -> ShowcaseLayout): http://localhost:3000/showcase/windham-willmantic-conn-food-access-map
    * You should see no changes compared to production: https://sdohplace.org/showcase/windham-willmantic-conn-food-access-map
    * NOTE: Images appear differently here, but these are not style changes - production appears to use different screenshot paths than dev
    * NOTE: Copyright symbol (at the bottom) has moved to the left a few pixels - I could not track down why, but this is barely noticeable

### CODE REVIEW

File: src/components/Layout.tsx [hunk 1]
```diff
@@ -0,0 +1,199 @@
...
+  news_props?: PostLayoutProps;
+  showcase_props?: ShowcaseLayoutProps;
+  /*guide_props?: GuideLayoutProps;*/
+  page_header?: string;
+  children?: React.ReactNode;
+};
+export default function Layout({ type, news_props, showcase_props, page_header, children }: Props) {
+  return (
+    <>
+      <Header title={"News"} />
```
Comment (mradamcox) [inline src/components/Layout.tsx:20]: This should reflect the content on the page and not always be "News" for all Layouts.

File: src/components/Layout.tsx [hunk 2]
```diff
@@ -0,0 +1,199 @@
...
+import NavBar from "@/components/NavBar";
+import TopLines from "@/components/TopLines";
+import Footer from "./homepage/footer";
+import React from "react";
+import PostLayout, {PostLayoutProps} from './news/PostLayout';
+import ShowcaseLayout, {ShowcaseLayoutProps} from './showcase/ShowcaseLayout';
+
+type Props = {
+  type?: 'news' | 'showcase' /* | 'guide' */;
+  news_props?: PostLayoutProps;
```
Comment (mradamcox) [inline src/components/Layout.tsx:11]: Looks good to me, thanks for reworking these!

**Review by mradamcox — CHANGES_REQUESTED** [review]
Just one small change needed, to update the title in the header, see comment.

File: src/components/Layout.tsx (hunk 1 above)
Comment (bodom0015) [reply src/components/Layout.tsx:20]: Oooh, good catch! thank you, I can quickly fix this one :pray:

Comment (bodom0015) [reply src/components/Layout.tsx]: I've added a simple function with a `switch` statement here to render the title properly based on the provided `type`.

If we would prefer, I can write a quick function to split the type into words and capitalize the first letter of each word. I held off on this, since it didn't seem necessary, but if we would prefer this approach we can do that instead :)

**Comment by bodom0015** [comment]
I'm noticing that the `font-size` of the page title has changed somewhere... checking to see if I may have lost a bit of needed CSS along the way 🤔

**Review by mradamcox — CHANGES_REQUESTED** [review]
The title should be the same as the current site, before the refactor. Please look at production site and follow that. One place where I see it's currently wrong on the production site is that /showcase is "Showcase | News | SDOH & Place Project", but that should just be "Showcase | SDOH & Place Project". Perhaps an overhaul of titles across the entire website would be good in the future, but for now we just need to at least not regress with this refactor.

**Comment by bodom0015** [comment]
@mradamcox I think I've fixed all the styling discrepancies here :+1: sorry for the additional delay on this - I completely agree that we don't want any styling changes here as a part of this merge

Regarding the `title`, it looks like this is set incorrectly in `config.json` (contains "News"). Should I go ahead and correct that here? I don't think this is a regression if the bug currently exists on the production site, but maybe I'm missing some context?

**Review by mradamcox — COMMENTED** [review]
merged to main branch, thanks!
